/* Source module: section and package progress view-model calculations.
 * Preserve existing return shapes, scoring rules, lazy-package caps, and global function names.
 * Side-effectful section saving and grading stay in the legacy runtime for now.
 */
function stateKey(code,type,idx){return code+'|'+type+'|'+idx}
function getSectionState(code,type,idx,storeArg){const st=(storeArg||readStore())[stateKey(code,type,idx)]||{};return {answers:st.answers||{},checked:st.checked||{},answerEvents:st.answerEvents||{}}}
function sectionStats(code,type,idx,storeArg){const sec=DB[code]?.[type]?.[idx];if(!sec)return {answered:0,total:0,pct:0,score:0};const saved=getSectionState(code,type,idx,storeArg);let answered=0,score=0;for(const q of sec.questions){const id=String(q[0]);const u=saved.answers[id];if(u!==undefined&&String(u).trim()!==''){answered++;if(isCorrect(q,u,type,idx))score++}}const total=sec.questions.length;return {answered,total,pct:total?Math.round(answered/total*100):0,score}}
function lazyPackageMeta(code){try{const meta=window.__hskDatabase?.byCode?.get(String(code));if(!meta)return null;const folder=String(meta.path||'').split('/')[1]||'';if(/^HSK\s*[45]$/i.test(folder))return {total:100,folder};if(/^Workbook\s*HSK4a$/i.test(folder)||/^Workbook\s*HSK4b$/i.test(folder))return {total:50,folder};return {total:0,folder}}catch(e){return null}}
function lazyStoredProgress(code,storeArg){const prefix=String(code)+'|',store=storeArg||readStore();let answered=0;for(const [key,raw] of Object.entries(store)){if(!key.startsWith(prefix)||!raw||typeof raw!=='object')continue;const a=raw.answers;if(!a||typeof a!=='object')continue;for(const v of Object.values(a)){if(v!==undefined&&String(v).trim()!=='')answered++}}return answered}
function packageStats(code,storeArg){const store=storeArg||readStore();let total=0,answered=0,score=0,gradedTotal=0;const rows=[];const pkg=DB[code];if(pkg?.__lazy){const meta=lazyPackageMeta(code);const expected=Number(meta?.total)||0;const savedAnswered=lazyStoredProgress(code,store);return {total:expected,answered:Math.min(savedAnswered,expected||savedAnswered),score:0,gradedTotal:0,pct:expected?Math.round(Math.min(savedAnswered,expected)/expected*100):0,scorePct:0,rows:[]}}for(const [type,m] of Object.entries(META)){const arr=pkg?.[type]||[];for(let i=0;i<arr.length;i++){const st=sectionStats(code,type,i,store);total+=st.total;answered+=st.answered;if(type!=='writing'||isSequenceWriting(type,i)){score+=st.score;gradedTotal+=st.total}rows.push({type,label:m.label,zh:m.zh,section:arr[i].title.replace(/^.*?·\s*/,''),range:arr[i].range,...st,graded:type!=='writing'||isSequenceWriting(type,i)})}}return {total,answered,score,gradedTotal,pct:total?Math.round(answered/total*100):0,scorePct:gradedTotal?Math.round(score/gradedTotal*100):0,rows}}
